services:
  Dbp\Relay\SublibraryConnectorCampusonlineBundle\Service\SublibraryProvider:
    autowire: true
    autoconfigure: true

  DBP\API\AlmaBundle\API\SublibraryProviderInterface:
    '@Dbp\Relay\SublibraryConnectorCampusonlineBundle\Service\SublibraryProvider'
