services:
  Dbp\Relay\SublibraryConnectorCampusonlineBundle\Service\SublibraryProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\SublibraryBundle\API\SublibraryProviderInterface:
    '@Dbp\Relay\SublibraryConnectorCampusonlineBundle\Service\SublibraryProvider'
